name: Add results of benchmarks to README

# Controls when the action will run
on:
  push:
    branches: ['master', 'main']
    paths: 
      - 'results/**.txt'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs commands using the runners shell
    - name: Run python script
      run: |
        python write-results.py 
    # Commit changes which were made in readme
    - name: Commit files 
      run: |
        git config --local user.name "github-action"
        git add .
        git commit -m "added results of benchmarks to readme (through action)"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true