name: Run benchmarks
on: [push, pull_request]
jobs:
  build:
    name: Run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set env
        run: |
          echo "TAG=v0.0.0" >> $GITHUB_ENV
          echo "REPO=helm" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE"
      - name: Set user
        run: |
          git config --global user.name "github-action"
          git config --global user.email "benchmarks@artipie.com"
          date +%s > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          commit-message: "bench: added results of benchmarks to readme (through action)"
          branch: bench-results-${{ env.TAG }}
          delete-branch: true
          title: "bench: results of benchmarks for version ${{ env.TAG }}"
          assignees: genryxy
          reviewers: genryxy
          labels: |
            report
