name: Run benchmarks
#on:
#  push:
#    tags:
#      - 'v*'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Run benchmark
    runs-on: [self-hosted, bench]
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set env
        run: |
          export TAG=v0.0.0
          export W_DIR=/home/runner
          export REPO=helm
          echo "$GITHUB_WORKSPACE"
          rm -rf benchmarks
          git clone https://github.com/artipie/benchmarks.git
          cd benchmarks/adapters
          echo "$REPO"
          make prepare TARGET=$REPO
